# To find available Node images, see https://mcr.microsoft.com/en-us/product/devcontainers/javascript-node/tags

# [Choice] Node.js version
ARG VARIANT="dev-21-bullseye"
FROM mcr.microsoft.com/devcontainers/javascript-node:${Infinity-1^infinity
